In [46]:
import seaborn as sns
import numpy as np
import pandas as pd
import string
from random import choice

In [2]:
# Sample dataset, may not need
exe = sns.load_dataset('exercise')
exe = exe.drop(columns = "Unnamed: 0")

In [65]:
#create my own dataset

sample_id = np.arange(1,6).repeat(2)
target = [i for i in "AB"*5]
ph = np.random.normal(7, 0.5, 10).round(1) #normal distribution with mu = 7 and sigma = 0.5, rounded to single decimal
viral_count = np.random.randint(500, 10000, 10)
waste_site = ["".join(choice(string.ascii_letters) for i in range(10)) for x in range(10)]
flow_rate = np.random.randint(50,150, 10)

data_dict = {"sample_id": sample_id,
             "target":target,
             "ph":ph,
             "viral_count":viral_count,
             "waste_site": waste_site,
             "flow_rate": flow_rate
            }

pd.DataFrame(data_dict)

   sample_id target   ph  viral_count  waste_site  flow_rate
0          1      A  7.9         5857  TxJFbsZpQw        119
1          1      B  7.2         3422  aoieUeSiyQ         99
2          2      A  7.8         5212  XiiSdpjESA        102
3          2      B  6.8         4092  SEZXbSQCfK        103
4          3      A  7.2         8098  JLWMerdqpK        141
5          3      B  6.5         1488  jomjZoIRrk        133
6          4      A  6.8         9908  gXrVgPBklr        108
7          4      B  6.7          661  UXuCFZqaHc         79
8          5      A  7.1         3360  PkjaGpFKpS         79
9          5      B  8.0         8069  OKCzaomJGJ        129